/* eslint-disable no-useless-escape */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { IAcademicProgramForm } from './academic-program.form';
import { ICourseForm } from './course.form';
import { IStudentForm } from './student.form';

export function AcademicProgramFormGroupFac(): FormGroup<IAcademicProgramForm> {
  return new FormGroup<IAcademicProgramForm>({
    id: new FormControl<number | null | undefined>(null),
    name: new FormControl<string | null | undefined>(null),
    courses: new FormArray<FormGroup<ICourseForm>>([]),
    students: new FormArray<FormGroup<IStudentForm>>([]),
  });
}
