/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { ICourseForm } from './course.form';
import { IStudentForm } from './student.form';

export interface IAcademicProgramForm {
    id: FormControl<number | null | undefined>;
    name: FormControl<string | null | undefined>;
    courses: FormArray<FormGroup<ICourseForm>>;
    students: FormArray<FormGroup<IStudentForm>>;
}
