/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { ICourse } from './course.model';
import { IStaff } from './staff.model';
import { IStudentClass } from './student-class.model';

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface IClass {
  id?: number | null;
  staffId?: number | null;
  courseId?: number | null;
  startDate?: Date | null;
  course?: Partial<ICourse>;
  staff?: Partial<IStaff>;
  studentClasses?: Partial<IStudentClass[]>;
}
