/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { ClassProperties } from './class.properties';

export function createTestClass() {
    return { 
      [ClassProperties.ID]: 0,
      [ClassProperties.STAFF_ID]: 0,
      [ClassProperties.COURSE_ID]: 0,
      [ClassProperties.START_DATE]: new Date(), 
      [ClassProperties.COURSE]: undefined,
      [ClassProperties.STAFF]: undefined,
      [ClassProperties.STUDENT_CLASSES]: [],
    };
}
