/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { ICourseForm } from './course.form';
import { IStaffForm } from './staff.form';
import { IStudentClassForm } from './student-class.form';

export interface IClassForm {
    id: FormControl<number | null | undefined>;
    staffId: FormControl<number | null | undefined>;
    courseId: FormControl<number | null | undefined>;
    startDate: FormControl<Date | null | undefined>;
    course: FormGroup<ICourseForm>;
    staff: FormGroup<IStaffForm>;
    studentClasses: FormArray<FormGroup<IStudentClassForm>>;
}
