/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum ClassProperties {
  ID = 'id',
  STAFF_ID = 'staffId',
  COURSE_ID = 'courseId',
  START_DATE = 'startDate',
  COURSE = 'course',
  STAFF = 'staff',
  STUDENT_CLASSES = 'studentClasses',
}
