/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { IClassForm } from './class.form';
import { IAcademicProgramForm } from './academic-program.form';

export interface ICourseForm {
    id: FormControl<number | null | undefined>;
    programId: FormControl<number | null | undefined>;
    name: FormControl<string | null | undefined>;
    classes: FormArray<FormGroup<IClassForm>>;
    program: FormGroup<IAcademicProgramForm>;
}
