/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { IClass } from './class.model';
import { IAcademicProgram } from './academic-program.model';

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface ICourse {
  id?: number | null;
  programId?: number | null;
  name?: string | null;
  classes?: Partial<IClass[]>;
  program?: Partial<IAcademicProgram>;
}
