/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #endpoints-ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum Endpoints {
  academicPrograms = '/AcademicPrograms',
  academicProgramsById = '/AcademicPrograms/ById',
  students = '/Students',
  studentsById = '/Students/ById',
}
export interface IEndpoints {
  readonly academicPrograms: string;
  readonly academicProgramsById: string;
  readonly students: string;
  readonly studentsById: string;
}
