/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #index.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export * from './academic-program.form-group-fac';
export * from './academic-program.form';
export * from './academic-program.model';
export * from './academic-program.properties';
export * from './academic-program.test-obj-fac';
export * from './class.form-group-fac';
export * from './class.form';
export * from './class.model';
export * from './class.properties';
export * from './class.test-obj-fac';
export * from './course.form-group-fac';
export * from './course.form';
export * from './course.model';
export * from './course.properties';
export * from './course.test-obj-fac';
export * from './staff.form-group-fac';
export * from './staff.form';
export * from './staff.model';
export * from './staff.properties';
export * from './staff.test-obj-fac';
export * from './student-class.form-group-fac';
export * from './student-class.form';
export * from './student-class.model';
export * from './student-class.properties';
export * from './student-class.test-obj-fac';
export * from './student.form-group-fac';
export * from './student.form';
export * from './student.model';
export * from './student.properties';
export * from './student.test-obj-fac';
