/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { IClassForm } from './class.form';

export interface IStaffForm {
    id: FormControl<number | null | undefined>;
    fullName: FormControl<string | null | undefined>;
    isProfessor: FormControl<boolean | null | undefined>;
    isDirector: FormControl<boolean | null | undefined>;
    classes: FormArray<FormGroup<IClassForm>>;
}
