/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { StaffProperties } from './staff.properties';

export function createTestStaff() {
    return { 
      [StaffProperties.ID]: 0,
      [StaffProperties.FULL_NAME]: 'FULL_NAME',
      [StaffProperties.IS_PROFESSOR]: false,
      [StaffProperties.IS_DIRECTOR]: false, 
      [StaffProperties.CLASSES]: [],
    };
}
