/* eslint-disable no-useless-escape */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { IStaffForm } from './staff.form';
import { IClassForm } from './class.form';

export function StaffFormGroupFac(): FormGroup<IStaffForm> {
  return new FormGroup<IStaffForm>({
    id: new FormControl<number | null | undefined>(null),
    fullName: new FormControl<string | null | undefined>(null),
    isProfessor: new FormControl<boolean | null | undefined>(null),
    isDirector: new FormControl<boolean | null | undefined>(null),
    classes: new FormArray<FormGroup<IClassForm>>([]),
  });
}
