/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum StaffProperties {
  ID = 'id',
  FULL_NAME = 'fullName',
  IS_PROFESSOR = 'isProfessor',
  IS_DIRECTOR = 'isDirector',
  CLASSES = 'classes',
}
