/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { StudentProperties } from './student.properties';

export function createTestStudent() {
    return { 
      [StudentProperties.ID]: 0,
      [StudentProperties.PROGRAM_ID]: 0,
      [StudentProperties.NAME]: 'NAME',
      [StudentProperties.DATE_OF_BIRTH]: new Date(),
      [StudentProperties.PHONE_NUMBER]: 'PHONE_NUMBER', 
      [StudentProperties.ACADEMIC_PROGRAM]: undefined,
      [StudentProperties.STUDENT_CLASSES]: [],
    };
}
