/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum StudentClassProperties {
  ID = 'id',
  STUDENT_ID = 'studentId',
  CLASS_ID = 'classId',
  GRADE = 'grade',
  CLASS = 'class',
  STUDENT = 'student',
}
