/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum StudentProperties {
  ID = 'id',
  PROGRAM_ID = 'programId',
  NAME = 'name',
  DATE_OF_BIRTH = 'dateOfBirth',
  PHONE_NUMBER = 'phoneNumber',
  ACADEMIC_PROGRAM = 'academicProgram',
  STUDENT_CLASSES = 'studentClasses',
}
