/* eslint-disable no-useless-escape */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { IStudentForm } from './student.form';
import { IAcademicProgramForm } from './academic-program.form';
import { AcademicProgramFormGroupFac } from './academic-program.form-group-fac';
import { IStudentClassForm } from './student-class.form';

export function StudentFormGroupFac(): FormGroup<IStudentForm> {
  return new FormGroup<IStudentForm>({
    id: new FormControl<number | null | undefined>(null),
    programId: new FormControl<number | null | undefined>(null),
    name: new FormControl<string | null | undefined>(null),
    dateOfBirth: new FormControl<Date | null | undefined>(null),
    phoneNumber: new FormControl<string | null | undefined>(null),
    academicProgram: new FormGroup<IAcademicProgramForm>(AcademicProgramFormGroupFac().controls),
    studentClasses: new FormArray<FormGroup<IStudentClassForm>>([]),
  });
}
