/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { IAcademicProgram } from './academic-program.model';
import { IStudentClass } from './student-class.model';

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface IStudent {
  id?: number | null;
  programId?: number | null;
  name?: string | null;
  dateOfBirth?: Date | null;
  phoneNumber?: string | null;
  academicProgram?: Partial<IAcademicProgram>;
  studentClasses?: Partial<IStudentClass[]>;
}
